POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFscGhhVXNlck5hbWUiLCJpZCI6IjY2OWI5MGJhZjAyZmMyYzVjYzcxZWFjNyJ9.1x5r6sypo34dWmoUEhmm8U0XgQiAEQwI1AUM-lEbz2U

{
	"title": "asAlphaBlogAnyUser",
	"author": "asAlphaAuthorAnyUser",
	"url": "asAlphaUrlAnyUser",
	"likes": "1"
}